### ISSUE TITLE
df_title_rank.csv，df_content_rank.csv这两个文件找不到

### ISSUE THREAD

**Issue by renektonwu** [Jacen789/HotNewsAnalysis#1]
def get_key_words():
    `df_title` = news_crawler.load_news(os.path.join(results_path, 'df_title_rank.csv'))
    `df_content` = news_crawler.load_news(os.path.join(results_path, 'df_content_rank.csv')) 

这两句话中的df_title_rank.csv，df_content_rank.csv这两个文件找不到，请问方便提供一下，进行学习吗

**Comment by Jacen789** [comment]
运行hot_news.py中的这两个函数就会生成出来了，这代码写了太久了，你要学会ctrl+f查找。
`
title_cluster(df, True)
content_cluster(df, True)
`
